### ISSUE TITLE
Include Doge and Tether

### ISSUE THREAD

**Issue by khoshrou** [go-faast/coin-payments#174]
Hi
Please Include Doge and Tether.

**Comment by dwolfgram** [comment]
Hello @khoshrou 

You can find doge here:
https://github.com/go-faast/coin-payments/tree/master/packages/doge-payments

For tether you are interested in the erc20 version?

**Comment by khoshrou** [comment]
I am very new in this area.
I like to have crypto payments for my web site, does this library suitable for this? 
is it using a backend broker or its standalone?
and is it possible to track who payed for a product? (kind of map registered users with wallet or transaction)
is there any working sample? (NextJS, Asp.net core, NodeJS, ...)
and sorry I didnot get this one "erc20 version"

**Comment by dylanseago** [comment]
@khoshrou This is a standalone library that for creating, signing, broadcasting, and looking up blockchain transactions, deriving addresses, checking address balances, and much more. It provides a single unified TypeScript interface for a number of blockchains and is designed to be stateless (ie not for mapping users transactions).

You can see some code examples here: https://github.com/go-faast/coin-payments/blob/master/packages/coin-payments/README.md

To make use of this library you'll need to integrate it into your backend service to manually track addresses, balances and the state of a transaction as it progresses throughout it's lifecycle (create -> sign -> broadcast -> confirmation).

If you're looking for a more beginner friendly solution that you can use to easily accept crypto payments on your website consider something like BitPay or Coinbase.

**Comment by khoshrou** [comment]
This sounds amazing. I prefer a standalone solution.
Thanks
