### ISSUE TITLE
TypeError: coinPayments.forAsset is not a function

### ISSUE THREAD

**Issue by RoseChilds** [go-faast/coin-payments#221]
The coinPayments object doesn't seem to have a forAsset function as shown in the documentation found in the README.md file and on NPM. 

```
const coinPayments = new CoinPayments({
    seed: 'my key'
  });

  const bchPayments = coinPayments.forAsset('BCH');
  await bchPayments.init();
```

This is the code I'm using, and it simply returns the error `TypeError: coinPayments.forAsset is not a function`. I'm using version 4.5.1.

**Comment by dzdidi** [comment]
@RoseChilds docs can be outdated.  Here is how tests are using it https://github.com/go-faast/coin-payments/blob/master/packages/coin-payments/test/CoinPayments.test.ts#L35

**Comment by RoseChilds** [comment]
Got it, thanks

**Comment by RoseChilds** [comment]
Hey there, just a quick question @dzdidi,
When attempting to send transactions, the API returns 503. Is this out of my hands or is there something I can do to fix this? The API page itself (https://bch1.trezor.io/) show no reason why this should happen
