### ISSUE TITLE
Send from all addresses in a single transaction

### ISSUE THREAD

**Issue by Gennttii** [go-faast/coin-payments#5]
Hi, 

I am able to create the xpub, and create as many addresses as I want, but what I want to do is to create a transaction with the amount from all the addresses in a single transfer.. How can I do that?

This creates a transaction from the address with ID 1234 only:
        let unsignedTx = await tronPayments.createSweepTransaction(1234, 12345)

**Comment by Gennttii** [comment]
@dylanseago

**Comment by dylanseago** [comment]
@Gennttii I don't believe that's possible on the TRON network. Transactions are one address to one address.
